require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe DutiesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Duty. As you add validations to Duty, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { name: 'Valid Name', pet: FactoryBot.create(:pet) }
  }

  let(:invalid_attributes) {
    { name: 1 }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DutiesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  before :each do
    @profile_user = FactoryBot.create(:profile_user)
	@pet = FactoryBot.create(:pet)
    allow(controller).to receive(:current_user) { @profile_user.user }
  end

  describe "GET #index" do
    it "returns a successful response" do
      duty = Duty.create! valid_attributes
      get :index, params: {pet_id: duty.pet.id}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #show" do
    it "returns a successful response" do
      duty = Duty.create! valid_attributes
      get :show, params: {id: duty.to_param, pet_id: duty.pet.id}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #new" do
    it "returns a successful response" do
      get :new, params: {pet_id: @pet.id}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #edit" do
    it "returns a successful response" do
      duty = Duty.create! valid_attributes
      get :edit, params: {id: duty.to_param, pet_id: duty.pet.id}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Duty" do
        expect {
          post :create, params: {pet_id: valid_attributes[:pet].id, duty: valid_attributes}, session: valid_session
        }.to change(Duty, :count).by(1)
      end

      it "redirects to the created duty" do
        post :create, params: {pet_id: valid_attributes[:pet].id, duty: valid_attributes}, session: valid_session
        expect(response).to redirect_to([Duty.last.pet, Duty.last])
      end
    end

    context "with invalid params" do
      it "returns a successful response (i.e. to display the 'new' template)" do
        post :create, params: {pet_id: valid_attributes[:pet].id, duty: invalid_attributes}, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
		@new_name = 'Another name'
	    { name: @new_name }
      }

      it "updates the requested duty" do
        duty = Duty.create! valid_attributes
        put :update, params: {id: duty.to_param, pet_id: duty.pet.id, duty: new_attributes}, session: valid_session
        duty.reload
        expect(duty.name).to eq(@new_name)	
      end

      it "redirects to the duty" do
        duty = Duty.create! valid_attributes
        put :update, params: {id: duty.to_param, pet_id: duty.pet.id, duty: valid_attributes}, session: valid_session
        expect(response).to redirect_to(duty)
      end
    end

    context "with invalid params" do
      it "returns a successful response (i.e. to display the 'edit' template)" do
        duty = Duty.create! valid_attributes
        put :update, params: {id: duty.to_param, duty: invalid_attributes}, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested duty" do
      duty = Duty.create! valid_attributes
      expect {
        delete :destroy, params: {id: duty.to_param}, session: valid_session
      }.to change(Duty, :count).by(-1)
    end

    it "redirects to the duties list" do
      duty = Duty.create! valid_attributes
      delete :destroy, params: {id: duty.to_param}, session: valid_session
      expect(response).to redirect_to(duties_url)
    end
  end

end
