require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe PetsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Pet. As you add validations to Pet, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { name: 'Valid Name', group: FactoryBot.create(:group), specie: FactoryBot.create(:specie) }
  }

  let(:invalid_attributes) {
    { name: 1 }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PetsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  before :each do
    @profile_user = FactoryBot.create(:profile_user)
	@group = FactoryBot.create(:group)
    allow(controller).to receive(:current_user) { @profile_user.user }
  end

  describe "GET #index" do
    it "returns a successful response" do
      pet = Pet.create! valid_attributes
      get :index, params: {group_id: pet.group.id}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #show" do
    it "returns a successful response" do
      pet = Pet.create! valid_attributes
      get :show, params: {id: pet.to_param, group_id: pet.group.id}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #new" do
    it "returns a successful response" do
      get :new, params: {group_id: @group.id}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #edit" do
    it "returns a successful response" do
      pet = Pet.create! valid_attributes
      get :edit, params: {id: pet.to_param, group_id: pet.group.id}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Pet" do
        expect {
          post :create, params: {group_id: valid_attributes[:group].id, pet: valid_attributes}, session: valid_session
        }.to change(Pet, :count).by(1)
      end

      it "redirects to the created pet" do
        post :create, params: {group_id: valid_attributes[:group].id, pet: valid_attributes}, session: valid_session
        expect(response).to redirect_to([Pet.last.group, Pet.last])
      end
    end

    context "with invalid params" do
      it "returns a successful response (i.e. to display the 'new' template)" do
        post :create, params: {group_id: valid_attributes[:group].id, pet: invalid_attributes}, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
		@new_name = 'Another name'
	    { name: @new_name }
      }

      it "updates the requested pet" do
        pet = Pet.create! valid_attributes
        put :update, params: {id: pet.to_param, group_id: pet.group.id, pet: new_attributes}, session: valid_session
        pet.reload
        expect(pet.name).to eq(@new_name)	
      end

      it "redirects to the pet" do
        pet = Pet.create! valid_attributes
        put :update, params: {id: pet.to_param, group_id: pet.group.id, pet: valid_attributes}, session: valid_session
        expect(response).to redirect_to([pet.group, pet])
      end
    end

    context "with invalid params" do
      it "returns a successful response (i.e. to display the 'edit' template)" do
        pet = Pet.create! valid_attributes
        put :update, params: {id: pet.to_param, group_id: pet.group.id, pet: invalid_attributes}, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested pet" do
      pet = Pet.create! valid_attributes
      expect {
        delete :destroy, params: {id: pet.to_param, group_id: pet.group.id}, session: valid_session
      }.to change(Pet, :count).by(-1)
    end

    it "redirects to the pets list" do
      pet = Pet.create! valid_attributes
      delete :destroy, params: {id: pet.to_param, group_id: pet.group.id}, session: valid_session
      expect(response).to redirect_to group_pets_path(pet.group.id)
    end
  end

end
